---
services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --web.enable-lifecycle
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
  prod-logs-node:
    image: prom/node-exporter
    hostname: prod-logs
    ports:
      - "9100:9100"
    command:
      - --web.listen-address=:9100
  prod-app-node:
    image: prom/node-exporter
    hostname: prod-app
    ports:
      - "9101:9100"
    command:
      - --web.listen-address=:9100
  dev-logs-node:
    image: prom/node-exporter
    hostname: dev-logs
    ports:
      - "9102:9100"
    command:
      - --web.listen-address=:9100
  dev-tests-node:
    image: prom/node-exporter
    hostname: dev-tests
    ports:
      - "9103:9100"
    command:
      - --web.listen-address=:9100
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
  shoehub:
    image: aussiearef/shoehub
    ports:
      - "5001:8080"
volumes:
  grafana_data:
