global:
  scrape_interval: "15s"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
          - localhost:9090
  - job_name: "demos"
    static_configs:
      - targets:
          - demo.promlabs.com:10000
          - demo.promlabs.com:10001
          - demo.promlabs.com:10002
  - job_name: "node_exporter"
    scrape_interval: "10s"
    static_configs:
      - targets: ["prod-logs-node:9100"]
      - targets: ["prod-app-node:9100"]
      - targets: ["dev-logs-node:9100"]
      - targets: ["dev-tests-node:9100"]
  - job_name: "shoehub"
    scrape_interval: "5s"
    static_configs:
      - targets: ["shoehub:8080"]
  - job_name: "grafana"
    scrape_interval: "5s"
    static_configs:
      - targets: ["grafana:3000"]
