apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  labels:
    type: multi-container
spec:
  containers:
    - name: alpine
      image: alpine
      command: ["tail"]
      args: ["-f", "/dev/null"]
    - name: busybox
      image: busybox
      command: ["tail"]
      args: ["-f", "/dev/null"]
