apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
  namespace: lablan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openldap
  template:
    metadata:
      labels:
        app: openldap
        function: auth
    spec:
      containers:
        - name: openldap
          image: bitnami/openldap:latest
          ports:
            - containerPort: 1389
            - containerPort: 1636
          env:
            - name: LDAP_ADMIN_USERNAME
              value: "admin"
            - name: LDAP_ADMIN_PASSWORD
              value: "lolz"
            - name: LDAP_ROOT
              value: "dc=ldap,dc=local"
            - name: LDAP_ADMIN_DN
              value: "cn=admin,dc=ldap,dc=local"
            - name: LDAP_USERS
              value: "user01,user02"
            - name: LDAP_PASSWORDS
              value: "password1,password2"
            - name: LDAP_ALLOW_ANON_BINDING
              value: "yes"
          volumeMounts:
            - name: openldap-storage
              mountPath: /bitnami/openldap
      volumes:
        - name: openldap-storage
          persistentVolumeClaim:
            claimName: openldap-data
