apiVersion: v1
kind: PersistentVolume
metadata:
  name: lablan-data
spec:
  capacity:
    storage: 8Gi  
  accessModes:
    - ReadWriteMany 
  hostPath:  
    path: /home/aoc/data
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openldap-data
  namespace: lablan
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi  
  storageClassName: local-path
  volumeName: lablan-data
