apiVersion: apps/v1
kind: Deployment 
metadata:
  name: alpine-deployment 
  labels:
    containers: alpines
spec:
  replicas: 5
  selector:
    matchLabels:
      apps: alpines
  template:
    metadata:
      labels:
        apps: alpines
    spec:
      containers:
        - name: alpine
          image: alpine:3.19
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
