---
- hosts: all
  become: true
  tasks:

  - name: update repository index
    ansible.builtin.apt:
      update_cache: yes

  - name: install tmux package
    ansible.builtin.apt:
      name: tmux
      state: latest
