- name: test connectivity
  hosts: homelab
  # gather_facts: false
  vars:
    motd: "hey whats up\n"
  tasks:
    - name: ping test
      ping:
    - name: display os release
      command: cat /etc/os-release
    - name: configure motd
      copy:
        content: "{{motd}}"
        dest: /etc/motd
      notify: MOTD changed
    - name: set a custom fact
      set_fact:
        webserver_app_port: 80
        webserver_app_path: /var/www/html
      when: ansible_distribution == 'Ubuntu'
    - name: show custom facts
      debug:
        msg:
          - "port: {{ webserver_app_port }}"
          - "path:{{ webserver_app_path }}"
  handlers:
    - name: MOTD changed
      debug:
        msg: "the motd was changed"
