apiVersion: v1
kind: Pod
metadata:
  name: dbg
  namespace: lablan
spec:
  containers:
    - name: alpine
      image: alpine:latest
      command: ["tail", "-f", "/dev/null"]
      lifecycle:
        postStart:
          exec:
            command: ["sh", "-c", "apk add --no-cache bind-tools"]
