apiVersion: v1
kind: Pod
metadata:
  labels:
    run: volx
  name: volx
  namespace: test
spec:
  containers:
  - image: nginx
    name: volx
    volumeMounts:
      - mountPath: /scratch
        name: scratch-volume
  - image: busybox
    name: bsx
    command: ["/bin/sh", "-c"]
    args: ["sleep 10000"]
    volumeMounts:
      - mountPath: /scratch
        name: scratch-volume
  volumes:
    - name: scratch-volume
      emptyDir:
        sizeLimit: 500Mi
