---
- hosts: all
  become: true
  pre_tasks:
    - name: install fedora updates
      ansible.builtin.dnf:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "Fedora"

    - name: install ubuntu updates
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

- hosts: homelab
  become: true
  tasks:
    - name: install apache
      ansible.builtin.apt:
        name:
          - apache2
          - libapache2-mod-php
      when: ansible_distribution == "Ubuntu"

- hosts: whatever
  become: true
  tasks:
    - name: install mariadb on whatever
      ansible.builtin.dnf:
        name: mariadb
        state: latest
      when: ansible_distribution == "Fedora"
