apiVersion: v1
kind: Service
metadata:
  name: phpldapadmin
  namespace: lablan
spec:
  type: NodePort  # You can change this to LoadBalancer if you are using a cloud provider
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080  # Optional: specify a port or let Kubernetes assign one
  selector:
    app: phpldapadmin
